In [1]:
import pandas as pd

prices = pd.read_csv(
    "../data/raw/prices.csv",
    index_col=0,
    parse_dates=True
)

prices.head()

                   GLD         IWM        QQQ         SPY        TLT
Date
2015-01-02  114.080002  102.786995  94.665070  170.125015  93.367279
2015-01-05  115.800003  101.412796  93.276443  167.052628  94.833992
2015-01-06  117.120003   99.658363  92.025764  165.479126  96.542625
2015-01-07  116.430000  100.885612  93.212097  167.541245  96.351944
2015-01-08  115.940002  102.596832  94.996132  170.514175  95.076004

In [2]:
returns = prices.pct_change()

returns.head()

                 GLD       IWM       QQQ       SPY       TLT
Date
2015-01-02       NaN       NaN       NaN       NaN       NaN
2015-01-05  0.015077 -0.013369 -0.014669 -0.018060  0.015709
2015-01-06  0.011399 -0.017300 -0.013408 -0.009419  0.018017
2015-01-07 -0.005891  0.012315  0.012891  0.012462 -0.001975
2015-01-08 -0.004209  0.016962  0.019140  0.017744 -0.013242

In [3]:
returns = returns.dropna()

returns.head()

                 GLD       IWM       QQQ       SPY       TLT
Date
2015-01-05  0.015077 -0.013369 -0.014669 -0.018060  0.015709
2015-01-06  0.011399 -0.017300 -0.013408 -0.009419  0.018017
2015-01-07 -0.005891  0.012315  0.012891  0.012462 -0.001975
2015-01-08 -0.004209  0.016962  0.019140  0.017744 -0.013242
2015-01-09  0.011385 -0.009603 -0.006583 -0.008013  0.010952

In [4]:
returns.describe()

               GLD          IWM          QQQ          SPY          TLT
count  2851.000000  2851.000000  2851.000000  2851.000000  2851.000000
mean      0.000517     0.000461     0.000795     0.000575     0.000016
std       0.010009     0.014154     0.013784     0.011144     0.009389
min      -0.102742    -0.132669    -0.119788    -0.109424    -0.066683
25%      -0.004666    -0.006906    -0.005021    -0.003700    -0.005625
50%       0.000565     0.000887     0.001228     0.000638     0.000337
75%       0.005552     0.008259     0.007835     0.005931     0.005564
max       0.063587     0.091491     0.120031     0.105019     0.075195

In [5]:
returns.mean()

GLD    0.000517
IWM    0.000461
QQQ    0.000795
SPY    0.000575
TLT    0.000016
dtype: float64

In [6]:
returns.std()

GLD    0.010009
IWM    0.014154
QQQ    0.013784
SPY    0.011144
TLT    0.009389
dtype: float64