In [1]:
import pandas as pd
import numpy as np

prices = pd.read_csv(
    "../data/raw/prices.csv",
    index_col=0,
    parse_dates=True
)

returns = prices.pct_change().dropna()

In [2]:
annual_return = returns.mean() * 252

annual_return

GLD    0.130166
IWM    0.116078
QQQ    0.200348
SPY    0.144921
TLT    0.003918
dtype: float64

In [3]:
annual_volatility = returns.std() * np.sqrt(252)

annual_volatility

GLD    0.158892
IWM    0.224685
QQQ    0.218813
SPY    0.176898
TLT    0.149051
dtype: float64

In [4]:
cumulative_returns = (1 + returns).cumprod()

rolling_max = cumulative_returns.cummax()

drawdowns = (cumulative_returns - rolling_max) / rolling_max

max_drawdown = drawdowns.min()

max_drawdown

GLD   -0.220022
IWM   -0.411333
QQQ   -0.351187
SPY   -0.337173
TLT   -0.483512
dtype: float64

In [5]:
risk_summary = pd.DataFrame({
    "Annual Return": annual_return,
    "Annual Volatility": annual_volatility,
    "Max Drawdown": max_drawdown
})

risk_summary

     Annual Return  Annual Volatility  Max Drawdown
GLD       0.130166           0.158892     -0.220022
IWM       0.116078           0.224685     -0.411333
QQQ       0.200348           0.218813     -0.351187
SPY       0.144921           0.176898     -0.337173
TLT       0.003918           0.149051     -0.483512

In [6]:
risk_summary["Return / Volatility"] = (
    risk_summary["Annual Return"] / risk_summary["Annual Volatility"]
)

risk_summary.sort_values("Return / Volatility", ascending=False)

     Annual Return  Annual Volatility  Max Drawdown  Return / Volatility
QQQ       0.200348           0.218813     -0.351187             0.915613
SPY       0.144921           0.176898     -0.337173             0.819231
GLD       0.130166           0.158892     -0.220022             0.819213
IWM       0.116078           0.224685     -0.411333             0.516624
TLT       0.003918           0.149051     -0.483512             0.026289